version: '3'

services:

  server:
    build:
      context: ./api
    depends_on:
      - db
    ports:
      - 1337:1337
    environment:
      DB_NAME: sails_db
      DB_USER: sails_user
      DB_PASSWORD: sails_password
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sails_root_password
      MYSQL_DATABASE: sails_db
      MYSQL_USER: sails_user
      MYSQL_PASSWORD: sails_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
